{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n>       assert False\nE       assert False\n\ntest_alluredemo1.py:9: AssertionError"}, "start": 1608790393557, "stop": 1608790393558, "uuid": "dbad494a-917c-4129-b681-d1838346a959", "historyId": "9e8d23832460ad3c87806390b91ae72c", "testCaseId": "d3ba699b3e70ee73490c0d009b152181", "fullName": "test_alluredemo1#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo1"}, {"name": "host", "value": "rong360deMacBook-Pro-104.local"}, {"name": "thread", "value": "69601-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo1"}]}